CONTIKI_PROJECT = hello-world
all: $(CONTIKI_PROJECT)

#TARGET = cc2538dk
TARGET = zoul
#BOARD = muntjac
#RADIO = cc1120
MODULES += os/services/shell

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
